SELECT numero_cuenta, saldo FROM cuentas;

--DEVUELVE 11 REGISTROS DE LOS 12 QUE ES LA FECHA ACTUAL MENOS 
--DOS MESES ES DECIR 9-2=7 Y ME DEVUELVE LA FECHA ENTRE 9 Y 7 QUE ES 8 MAS LOS REGISTROS CON LA FECHA ACTUAL
SELECT * 
FROM cuentas 
WHERE fecha_creacion BETWEEN NOW() - INTERVAL '2 months' AND NOW();

--DEVUELVE 11 REGISTROS DE LOS 12 QUE ES LA FECHA ACTUAL MENOS 
--DOS MESES ES DECIR 9-2=7 Y ME DEVUELVE LA FECHA ENTRE 9 Y 7 QUE ES 8 MAS LOS REGISTROS CON LA FECHA ACTUAL

SELECT numero_cuenta,saldo
FROM cuentas 
WHERE fecha_creacion BETWEEN NOW() - INTERVAL '2 months' AND NOW();






